// The voices (comp:voices) — the sound engine.
//
// Provides iface:play-a-voice. Governed by dec:two-speed-synthesis: the drums
// are loaded from files the forge baked, and the pitched voices are generated
// here — but generated ONCE, at load, into buffers. Nothing is synthesized on
// the hot path.
//
// That is a stronger reading of the timing decision than the design asked for.
// A live oscillator graph per note is the obvious way to build a pitched voice
// and it puts node construction between her thumb and the sound; pre-rendering
// every note she can possibly play turns that into a buffer lookup. Seven scale
// degrees at under a second each costs a few milliseconds and a couple of
// megabytes, which is nothing, and it means the expensive path runs while she is
// still reading the first screen.
//
// This part never reads her track and never reads the screen.

import { renderClick, degreeToHz, SCALE_STEPS, PROGRESSION, NEUTRAL } from './dsp.js';
import { PHONK } from './palettes.js';

/**
 * Degrees we pre-render — one octave of whatever scale the palette is using.
 *
 * A FUNCTION rather than a constant, because the scale is now a palette's choice
 * and this used to be captured at module load. A six-note scale would have had
 * its top note silently unrendered.
 */
const degrees = () => SCALE_STEPS.map((_, i) => i);

/**
 * Per-voice level, applied on top of whatever the caller asks for.
 *
 * The drums sit a quarter down from where they were. Each one is normalised to
 * near full scale on its own, which is right for a one-shot heard alone and too
 * loud for four of them landing together over an 808 — the owner's verdict on
 * playing it was simply that the drums were too much. Pulling them back here
 * rather than at the master keeps the 808 and the lead where they are.
 */
const VOICE_GAIN = {
  kick: 0.75,
  snare: 0.75,
  hat: 0.75,
  openhat: 0.75,
  cowbell: 0.75,
  clap: 0.75,
};

/**
 * The note lengths pitched voices are rendered at, in seconds.
 *
 * A held key already drew a longer block on screen and made exactly the same
 * sound, because the amplitude envelope is baked into the sample. That left the
 * decision "a pitched note has a length the player chooses" only half built.
 *
 * Rendering a few lengths rather than moving the envelope onto a gain node is
 * the cheaper of the two answers, and it keeps the character: each length is
 * rendered with its OWN proper envelope, so a long 808 decays like a long 808
 * rather than like a short one stretched. The steps are coarse and the ear does
 * not notice — what it notices is a two-bar note that stops after a beat.
 *
 * Seconds rather than beats, deliberately: tempo is set after these are built,
 * and tying them to it would mean re-rendering every time she retaps.
 */
const LENGTHS = [0.25, 0.5, 1.0, 2.0];

/** Which rendered length is closest to what she actually held. */
function nearestLength(seconds) {
  if (!(seconds > 0)) return 0;
  let best = 0;
  for (let i = 1; i < LENGTHS.length; i++) {
    if (Math.abs(LENGTHS[i] - seconds) < Math.abs(LENGTHS[best] - seconds)) best = i;
  }
  return best;
}

export class Voices {
  /**
   * @param {AudioContext} ctx
   * @param {{kitUrl?: string}} opts
   */
  constructor(ctx, { palette = PHONK, kitUrl } = {}) {
    this.ctx = ctx;
    /** Which style this engine is voicing (dec:styles-are-palettes). */
    this.palette = palette;
    this.kitUrl = kitUrl ?? palette.kit;

    /** @type {Map<string, AudioBuffer>} baked drums, by voice name */
    this.drums = new Map();
    /** @type {Map<string, AudioBuffer>} pitched, keyed `${voice}:${degree}` */
    this.pitched = new Map();

    this.ready = false;
    // One shaping set per pitched voice the palette declares, rather than the
    // two the phonk kit happened to have.
    this.shaping = Object.fromEntries(
      Object.keys(palette.pitched).map((name) => [name, { ...NEUTRAL }])
    );

    // Master chain: gain into a soft-clipper into the speakers.
    //
    // The clipper is not protection, it is the sound. Running the whole mix
    // through one shared saturation is a lot of what makes a set of separate
    // hits read as a track rather than as a list of noises — it is the single
    // biggest difference between the demo render and a naive playback.
    this.master = ctx.createGain();
    this.master.gain.value = 0.85;
    this.clipper = ctx.createWaveShaper();
    this.clipper.curve = softClipCurve(1.15);
    this.clipper.oversample = '2x';
    this.master.connect(this.clipper).connect(ctx.destination);

    // THE ROOM (dec:ethereal-not-a-sleep-lab). A palette that declares one gets a
    // convolver on a send, fed an impulse response generated by the same filters
    // the offline forge uses — so the page and the rendered demo cannot drift
    // into two different-sounding spaces. A palette with `room: null` pays for
    // nothing: no node is created and the signal path is exactly what it was.
    this.wet = null;
    if (palette.room && palette.impulse) {
      this.wet = ctx.createGain();
      this.wet.gain.value = palette.room.mix ?? 0.4;
      this.convolver = ctx.createConvolver();
      const [L, R] = palette.impulse(ctx.sampleRate);
      const ir = ctx.createBuffer(2, L.length, ctx.sampleRate);
      ir.copyToChannel(L, 0);
      ir.copyToChannel(R, 1);
      this.convolver.buffer = ir;
      this.wet.connect(this.convolver).connect(this.master);
    }

    // The click sits OUTSIDE the master clipper. It is not part of the music and
    // must not be squashed by, or contribute to, the mix glue — it has to stay
    // legible under drums at a level that never competes with them.
    this.clickBus = ctx.createGain();
    this.clickBus.gain.value = 0;
    this.clickBus.connect(ctx.destination);

    // The drone is a floor, not a layer: through the glue, well down.
    this.droneBus = ctx.createGain();
    this.droneBus.gain.value = 0;
    this.droneBus.connect(this.master);
    this._drone = null;
  }

  /**
   * Load the baked kit and render the pitched voices.
   * Safe to call before the first tap — decoding does not need a running context.
   */
  async load() {
    // A palette need not have a baked kit at all: the calm one is pitched all
    // the way through, so there is nothing to fetch.
    if (this.kitUrl) {
      const manifest = await fetch(this.kitUrl).then((r) => {
        if (!r.ok) throw new Error(`kit manifest ${r.status}`);
        return r.json();
      });
      const base = this.kitUrl.replace(/[^/]*$/, '');

      await Promise.all(
        Object.entries(manifest.voices).map(async ([name, file]) => {
          const bytes = await fetch(base + file).then((r) => r.arrayBuffer());
          // decodeAudioData resamples to the context rate for us, which is why
          // the forge is free to bake at 22050 to keep the kit small.
          this.drums.set(name, await this.ctx.decodeAudioData(bytes));
        })
      );
    }

    const sr = this.ctx.sampleRate;
    this.click = toBuffer(this.ctx, renderClick(sr, {}), sr);
    this.clickAccent = toBuffer(this.ctx, renderClick(sr, { accent: true }), sr);
    this.pad = toBuffer(this.ctx, this.palette.drone(sr), sr);

    this.renderPitched();
  }

  // -------------------------------------------------------------------------
  // The click and the drone
  // -------------------------------------------------------------------------

  /** One tick of the metronome. `accent` marks beat one. */
  playClick(time, { accent = false } = {}) {
    const buf = accent ? this.clickAccent : this.click;
    if (!buf) return;
    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    src.connect(this.clickBus);
    src.start(Math.max(time ?? this.ctx.currentTime, this.ctx.currentTime));
  }

  /**
   * Fade the click in or out over `seconds`.
   *
   * Fading rather than switching because the click RETIRES once her beat can
   * keep time for her (dec:she-sets-the-tempo), and a metronome that vanishes
   * between one beat and the next reads as a fault rather than as a handover.
   */
  setClickLevel(level, seconds = 0.6) {
    const g = this.clickBus.gain;
    g.cancelScheduledValues(this.ctx.currentTime);
    g.setValueAtTime(g.value, this.ctx.currentTime);
    g.linearRampToValueAtTime(level, this.ctx.currentTime + seconds);
  }

  /** Start the pedal point. Loops forever; only its level ever changes. */
  startDrone(level = 0.18) {
    if (this._drone || !this.pad) return;
    const src = this.ctx.createBufferSource();
    src.buffer = this.pad;
    src.loop = true;
    src.connect(this.droneBus);
    src.start();
    this._drone = src;
    this.setDroneLevel(level, 2.5); // in slowly: a pad that arrives suddenly is a noise
  }

  setDroneLevel(level, seconds = 1.5) {
    const g = this.droneBus.gain;
    g.cancelScheduledValues(this.ctx.currentTime);
    g.setValueAtTime(g.value, this.ctx.currentTime);
    g.linearRampToValueAtTime(level, this.ctx.currentTime + seconds);
  }

  /**
   * (Re)render every pitched note from the current shaping numbers.
   *
   * Called at load, and again when she turns a control. It is synchronous and
   * takes a few milliseconds — acceptable while she is dragging a slider, and
   * deliberately never called while a note is starting.
   */
  renderPitched() {
    // THE BASS MOVES AND THE MELODY DOES NOT, which is how a band actually does
    // this. The bass states the chord — that is what makes the harmony audible
    // at all — while the melody stays in one scale and floats over the changes.
    // It is why a blues player uses a single pentatonic over a whole tune, and
    // it is what keeps every note she can press consonant against every chord.
    this._renderPass(this.priorityLengths());
    this.ready = true;
    this._fillRemaining();
  }

  /**
   * The lengths worth rendering for a voice.
   *
   * A NOTE SHORTER THAN ITS OWN ATTACK IS SILENCE. The calm pad swells over
   * about 0.7 seconds and the singing bowl over a full second, so rendering them
   * at 0.25s produces a buffer that costs time and memory to make and then makes
   * no sound. Phonk voices attack in milliseconds and want every length.
   */
  lengthsFor(name) {
    const attack = this.palette.pitched[name]?.attack ?? 0;
    const usable = LENGTHS.map((_, i) => i).filter((i) => LENGTHS[i] > attack * 1.4);
    // Never return nothing: the longest is always playable whatever the attack.
    return usable.length ? usable : [LENGTHS.length - 1];
  }

  /**
   * WHICH LENGTH SHE TOUCHES FIRST, and it is the longest.
   *
   * Every sustaining round starts its note through startHeld, which always takes
   * the longest rendered buffer because at the moment she presses, nothing knows
   * how long she will hold. So the longest is the one that has to exist before
   * the gate opens; the rest can arrive while she is reading it.
   */
  priorityLengths() {
    return [LENGTHS.length - 1];
  }

  /** Render one set of length indices for every pitched voice. */
  _renderPass(lengthIdx) {
    for (let chord = 0; chord < PROGRESSION.length; chord++) {
      const shift = Math.pow(2, PROGRESSION[chord] / 12);
      for (const [name, spec] of Object.entries(this.palette.pitched)) {
        // A palette may render at a lower rate than the context runs at. Every
        // calm voice tops out below 8.4 kHz, so 22050 is transparent for them
        // and halves both the time and the memory — the same trade the baked
        // drum kit already makes. Web Audio resamples on playback.
        const sr = spec.sampleRate ?? this.ctx.sampleRate;
        const wanted = this.lengthsFor(name);
        for (const len of lengthIdx) {
          if (!wanted.includes(len)) continue;
          for (const degree of degrees()) {
            const key = `${name}:${degree}:${chord}:${len}`;
            if (this.pitched.has(key)) continue;
            const hz = degreeToHz(degree, spec.octaves ?? 0) * shift;
            this.pitched.set(
              key,
              toBuffer(this.ctx, spec.render(sr, hz, this.shaping[name], { seconds: LENGTHS[len] }), sr)
            );
          }
        }
      }
    }
  }

  /**
   * Fill in every remaining length AFTER she can already play.
   *
   * One voice per turn of the event loop rather than one big block, so the page
   * stays responsive while it happens. Time to first sound is what a player
   * feels; total work is not, as long as none of it lands between her thumb and
   * the sound (dec:built-for-tight-timing).
   *
   * If she manages to hold a note before its exact length exists, `play` falls
   * back to the nearest one that does — a slightly wrong length is inaudible,
   * and silence would not be.
   */
  _fillRemaining() {
    const rest = LENGTHS.map((_, i) => i).filter((i) => !this.priorityLengths().includes(i));
    if (!rest.length) return;
    const queue = [...rest];
    const step = () => {
      const len = queue.shift();
      if (len === undefined) { this.fullyRendered = true; return; }
      this._renderPass([len]);
      (globalThis.requestIdleCallback ?? ((f) => setTimeout(f, 0)))(step);
    };
    (globalThis.requestIdleCallback ?? ((f) => setTimeout(f, 0)))(step);
  }

  /**
   * The buffer for a note, or the nearest length that has been rendered.
   *
   * Never returns undefined when the voice exists at all, which is what lets
   * rendering be progressive without any chance of a silent key.
   */
  buffer(voice, degree, chord, len) {
    const exact = this.pitched.get(`${voice}:${degree}:${chord}:${len}`);
    if (exact) return exact;
    for (let d = 1; d < LENGTHS.length; d++) {
      for (const alt of [len - d, len + d]) {
        if (alt < 0 || alt >= LENGTHS.length) continue;
        const b = this.pitched.get(`${voice}:${degree}:${chord}:${alt}`);
        if (b) return b;
      }
    }
    return undefined;
  }

  /** Set one instrument's shaping numbers and re-render it. */
  setShaping(instrument, values) {
    if (!this.shaping[instrument]) return;
    Object.assign(this.shaping[instrument], values);
    // Drop this instrument's buffers so the new numbers are actually heard —
    // _renderPass skips keys it already has, which is what makes the progressive
    // fill cheap and would otherwise make a shaping change do nothing.
    for (const key of [...this.pitched.keys()]) {
      if (key.startsWith(`${instrument}:`)) this.pitched.delete(key);
    }
    this.renderPitched();
  }

  /**
   * Play one voice, at one pitch, at one audio time.
   *
   * A voice that is not loaded is silent rather than throwing (iface:play-a-voice).
   * The one thing this must never do is make a sound late in order to be correct,
   * so there is no awaiting and no lazy loading here.
   *
   * @param {string} voice  'kick' | 'snare' | ... | 'bass' | 'lead'
   * @param {{degree?, time?, gain?, chord?, seconds?}} opts
   *   chord   — which chord is sounding. Drums ignore it; a kick does not transpose.
   *   seconds — how long the note should last. Ignored by drums, which have a
   *             length of their own; rounded to the nearest rendered length for
   *             pitched voices, which is how a held note finally sounds held.
   */
  play(voice, { degree = 0, time, gain = 1, chord = 0, seconds } = {}) {
    const at = time ?? this.ctx.currentTime;
    const n = degrees().length;
    const c = ((chord % PROGRESSION.length) + PROGRESSION.length) % PROGRESSION.length;
    const len = nearestLength(seconds ?? LENGTHS[1]);
    const buf =
      this.drums.get(voice) ??
      this.buffer(voice, ((degree % n) + n) % n, c, len);
    if (!buf) return;

    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    const level = gain * (VOICE_GAIN[voice] ?? 1);
    const g = this.ctx.createGain();
    g.gain.value = level;
    src.connect(g);
    g.connect(this.master);
    if (this.wet) g.connect(this.wet);
    // Never schedule into the past: iOS treats a negative start time as an
    // error on some versions rather than clamping it.
    src.start(Math.max(at, this.ctx.currentTime));
  }
}

/**
 * Start a note that lasts as long as she holds the key, and hand back the way
 * to end it.
 *
 * The longest rendered length is started, and release ramps it down over a few
 * tens of milliseconds — long enough not to click, short enough to feel like
 * letting go. This is the LIVE half of holding: at the moment she presses,
 * nothing knows how long the note will be, so it cannot be chosen in advance.
 * The recorded half picks a rendered length once the run is known.
 */
Voices.prototype.startHeld = function startHeld(voice, { degree = 0, chord = 0, gain = 1 } = {}) {
  const n = degrees().length;
  const c = ((chord % PROGRESSION.length) + PROGRESSION.length) % PROGRESSION.length;
  const buf = this.buffer(voice, ((degree % n) + n) % n, c, LENGTHS.length - 1);
  if (!buf) return { release() {} };

  const src = this.ctx.createBufferSource();
  const g = this.ctx.createGain();
  src.buffer = buf;
  g.gain.value = gain * (VOICE_GAIN[voice] ?? 1);
  src.connect(g);
  g.connect(this.master);
  if (this.wet) g.connect(this.wet);
  src.start();

  let done = false;
  return {
    release: () => {
      if (done) return;
      done = true;
      const t = this.ctx.currentTime;
      g.gain.cancelScheduledValues(t);
      g.gain.setValueAtTime(g.gain.value, t);
      g.gain.linearRampToValueAtTime(0, t + 0.06);
      try { src.stop(t + 0.08); } catch { /* already stopped */ }
    },
  };
};

/** Wrap a Float32Array of samples as a mono AudioBuffer. */
function toBuffer(ctx, samples, sampleRate) {
  const buf = ctx.createBuffer(1, samples.length, sampleRate);
  buf.copyToChannel(samples, 0);
  return buf;
}

/** tanh curve for the master WaveShaper — same shape as the forge's bus glue. */
function softClipCurve(drive, n = 2048) {
  const curve = new Float32Array(n);
  const norm = Math.tanh(drive);
  for (let i = 0; i < n; i++) {
    const x = (i / (n - 1)) * 2 - 1;
    curve[i] = Math.tanh(x * drive) / norm;
  }
  return curve;
}
