// Generate one page per palette, so each style gets a clean URL.
//
// Run:  node forge/pages.mjs
//
// /jugbeats/           the phonk game — index.html, the source of truth
// /jugbeats/ethereal/  the calm one   — generated from it
//
// GENERATED BUT COMMITTED, which is the same arrangement `kit/` already has and
// for the same reason: GitHub Pages serves this repository as-is with no build
// step, so anything the site needs has to be in the tree. index.html is the one
// hand-edited page; run this after changing it and never edit the output.
//
// WHY A DIRECTORY RATHER THAN A QUERY STRING. `?p=calm` works and still does,
// but a link you send someone should look like a place rather than a setting.
// And why not a separate repository at /ethereal — because that is a second copy
// of the whole project, which is exactly what dec:styles-are-palettes exists to
// avoid. A subdirectory shares every byte of the engine.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://sligara7.github.io/jugbeats';

/**
 * Which palettes get a page of their own.
 *
 * ROOT STAYS THE PHONK GAME AND ALWAYS WILL. Every link she has already sent is
 * `/jugbeats/#...`, and those have to keep working — that is the whole promise
 * iface:track-format makes. So `/beats/` is an ALIAS for the sake of a symmetric
 * pair of names, not a move.
 */
const PAGES = [
  {
    dir: 'beats',
    palette: 'phonk',
    title: 'JugBeats — make a phonk beat',
    ogTitle: 'JugBeats',
    ogDescription:
      'Turn your phone sideways, tap the blocks, make a phonk beat. Then send it back.',
    h1: 'JugBeats',
    hint: 'turn your volume up — and if it stays quiet, tap “no sound?” after you start',
  },
  {
    dir: 'reggaeton',
    palette: 'reggaeton',
    title: 'JugDembow — you cannot miss the beat',
    ogTitle: 'JugDembow',
    ogDescription:
      'Turn your phone sideways, tap the blocks, and you cannot miss the beat. Then send it back.',
    h1: 'JugDembow',
    hint: 'the first round snaps to the dembow — tap anywhere near it',
  },
  {
    dir: 'haunted',
    palette: 'haunted',
    title: 'JugHaunt — make something not quite right',
    ogTitle: 'JugHaunt',
    ogDescription:
      'Turn your phone sideways, tap the blocks, make something that is not quite right.',
    h1: 'JugHaunt',
    hint: 'turn your volume up — this one is better in the dark',
  },
  {
    dir: 'ethereal',
    palette: 'calm',
    title: 'JugCalm — make something peaceful',
    ogTitle: 'JugCalm',
    ogDescription:
      'Turn your phone sideways, tap the blocks, make something peaceful. Then send it back.',
    h1: 'JugCalm',
    hint: 'turn your volume up — headphones if you have them',
  },
];

const source = readFileSync(join(ROOT, 'index.html'), 'utf8');

for (const page of PAGES) {
  let html = source;

  // The palette the page IS. js/main.js reads this off <html> before it builds
  // anything, because the round list depends on it and everything depends on
  // the round list.
  html = html.replace('<html lang="en">', `<html lang="en" data-palette="${page.palette}">`);

  // Every reference climbs one directory, because this page lives in one.
  html = html.replace(/(href|src)="((?:css|js|kit)\/)/g, '$1="../$2');

  html = html.replace(/<title>[^<]*<\/title>/, `<title>${page.title}</title>`);

  // The chat preview card. WhatsApp caches these hard, so they have to be right
  // BEFORE the link is shared, and they have to be ABSOLUTE.
  const meta = {
    'og:title': page.ogTitle,
    'og:description': page.ogDescription,
    'og:url': `${SITE}/${page.dir}/`,
    'twitter:card': 'summary_large_image',
  };
  for (const [prop, content] of Object.entries(meta)) {
    const attr = prop.startsWith('og:') ? 'property' : 'name';
    html = html.replace(
      new RegExp(`<meta ${attr}="${prop}" content="[^"]*">`),
      `<meta ${attr}="${prop}" content="${content}">`,
    );
  }

  // The gate is the first thing anyone sees; it should say where they are.
  html = html.replace(/<h1 id="gate-title">[^<]*<\/h1>/, `<h1 id="gate-title">${page.h1}</h1>`);
  html = html.replace(
    /<p class="hint">[^<]*<\/p>/,
    `<p class="hint">${page.hint}</p>`,
  );

  html = html.replace(
    '<!doctype html>',
    `<!doctype html>\n<!-- GENERATED by forge/pages.mjs from index.html. Do not edit; edit that. -->`,
  );

  mkdirSync(join(ROOT, page.dir), { recursive: true });
  writeFileSync(join(ROOT, page.dir, 'index.html'), html);
  console.log(`wrote ${page.dir}/index.html — ${SITE}/${page.dir}/`);
}
